name: .NET

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev

env:
  Version: '1.0.0'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set pre-release version
        run: echo "PACKAGE_VERSION=${{ env.Version }}-alpha-${{ github.run_number }}" >> $GITHUB_ENV
        if: github.base_ref  == 'dev'
      - name: Set release version
        run: echo "PACKAGE_VERSION=${{ env.Version }}.${{ github.run_number }}" >> $GITHUB_ENV
        if: github.base_ref  == 'main'
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release -p:Version=${{ env.PACKAGE_VERSION }}
      - name: Pack
        run: dotnet pack -c Release -p:Version=${{ env.PACKAGE_VERSION }}
      - name: Push to nuget 
        run: dotnet nuget push Bromix.Blazor.BrowserAPI/bin/Release/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
      # - name: Provide download
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: nugetpackage
      #     path: '**/*.nupkg'